### PR TITLE
[Bug Fix] Some unusual characters are appeared on mouse-drag

### PR DESCRIPTION
**Pull request by dinukadesilva**

### CODE REVIEW

**Comment by dinukadesilva** [comment]
@simonbates 

Seems like this has fixed #59 and #55

**Comment by simonbates** [comment]
My hope is that we could address this issue by using preventDefault on browser events rather than with non-standard browser-specific CSS rules.

I'm thinking preventDefault on mousedown but there is also a more recent drag event that could be tried:

https://developer.mozilla.org/en-US/docs/Web/Events/drag

**Comment by simonbates** [comment]
I experimented with using preventDefault on mousedown for the knob control and was able to get rid of the undesirable dragging behaviour by adding the following to the `sisiliano.knob.addListeners` function:

```
that.locate("svg").mousedown(function (evt) {
    evt.preventDefault();
    that.container.focus();
});
```

**Comment by dinukadesilva** [comment]
Thanks @simonbates

**Pull request merged**
